feature: ['feature/*', 'feat/*', 'new/*']
bug: ['fix/*', 'bugfix/*', 'bug/*']
maintenance: ['chore/*', 'maint/*', 'noop/*', 'no-op/*', 'upkeep/*', 'dev/*']
documentation: ['docs/*', 'doc/*']
dependencies: ['deps/*', 'dependencies/*']
