name-template: 'Release v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
template: |
  ## Get it

  Install it with pip

  ```bash
  pip install mkdocs-simple-plugin==$NEXT_PATCH_VERSION
  ```
  See it on pypi: [https://pypi.org/project/mkdocs-simple-plugin](https://pypi.org/project/mkdocs-simple-plugin/$NEXT_PATCH_VERSION/)

  ## What’s Changed

  $CHANGES
