name-template: "Release v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
template: |
  ## Get it

  ### Python

  Install it with pip

  ```bash
  pip install mkdocs-simple-plugin==$RESOLVED_VERSION
  ```
  See it on pypi: [https://pypi.org/project/mkdocs-simple-plugin](https://pypi.org/project/mkdocs-simple-plugin/$RESOLVED_VERSION/)

  ### Docker 

  Pull it with docker

  ```bash
  docker pull athackst/mkdocs-simple-plugin:latest
  ```

  See it on dockerhub: [https://hub.docker.com/repository/docker/athackst/mkdocs-simple-plugin](https://hub.docker.com/repository/docker/athackst/mkdocs-simple-plugin)

  ### Github

  See it in the actions marketplace: [https://github.com/marketplace/actions/mkdocs-simple-action](https://github.com/marketplace/actions/mkdocs-simple-action)

  ## What’s Changed

  $CHANGES
categories:
  - title: ':zap: Breaking'
    label: 'breaking'
  - title: ':rocket: New'
    label: 'feature'
  - title: ':bug: Bug Fixes'
    label: 'bug'
  - title: ':toolbox: Maintenance'
    label: 'maintenance'
  - title: ':memo: Documentation'
    label: 'docs'
  - title: 'Dependency Updates'
    label: 'dependencies'

version-resolver:
  major:
    labels:
      - 'breaking'
      - 'major'
  minor:
    labels:
      - 'feature'
      - 'minor'
  patch:
    labels:
      - 'bug'
      - 'maintenance'
      - 'docs'
      - 'dependencies'
      - 'security'

exclude-labels:
  - 'skip-changelog'
