name: "MkDocs Simple action"
description: "Generate a configuration free mkdocs site"
branding:
  icon: "book"
  color: "green"
inputs:
  publish_branch:
    description: "Set a target branch for deployment."
    required: false
    default: "gh-pages"
  repo_url:
    description: "Set the repository url."
    required: false
    default: "https://github.com/${{ github.repository }}"
  site_name:
    description: "Set the site name."
    required: false
    default: "${{ github.repository }}"
  site_url:
    description: "Set the site url."
    required: false
    default: "https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}"
runs:
  using: "docker"
  image: "Dockerfile"
  env:
    BRANCH_NAME: ${{ inputs.publish_branch }}
    REPO_URL: ${{ inputs.repo_url }}
    SITE_NAME: ${{ inputs.site_name }}
    SITE_URL: ${{ inputs.site_url }}
  args:
    - deploy.sh
