# md
# ## Deploy from GitHub Actions
# 
# Create a YAML file with the following contents in the `.github/workflows` directory in your repository
# 
# ```yaml
# jobs:
#   docs:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2
#       - name: Build docs
#         uses: athackst/mkdocs-simple-plugin
#         with:
#           # (optional) Specify branch 
#           publish_branch: gh-pages 
#           # (optional) The URL of the repository the docs should point to
#           repo_url: https://github.com/owner/repository 
#           # (optional) The name of the site
#           site_name: owner/repository 
#           # (optional) The URL of the site
#           site_url: https://owner.github.io/repository 
#           # (optional) The edit URI
#           edit_uri: edit/main/
#           # (optional) Specify a google analytics key 
#           google_analytics: UA-XXXXXXX
#           # (optional) Specify a different theme [mkdocs|readthedocs|material]
#           theme: material
#           # (optional) Load a configuration file from a string
#           config: "{additional_css: value}"
#           # (optional) Version or alias.  Specify multiple aliases with space
#           # example: version: v0.1.0 latest
#           version: latest
#           # (optional) The version that will be served by the root of your site
#           default_version: latest
#           # (optional) Whether to push the docs to the remote branch
#           push: 1
# ```
# /md
name: "MkDocs Simple action"
description: "Generate a configuration free mkdocs site"
branding:
  icon: "book"
  color: "green"
inputs:
  publish_branch:
    description: "Set a target branch for deployment."
    required: false
    default: "gh-pages"
  repo_url:
    description: "Set the repository url."
    required: false
    default: "https://github.com/${{ github.repository }}"
  site_name:
    description: "Set the site name."
    required: false
    default: "${{ github.repository }}"
  site_url:
    description: "Set the site url."
    required: false
    default: "https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}"
  site_dir:
    description: "Directory to build the site."
    required: false
  edit_uri:
    description: "Set the edit uri"
    required: false
    default: "edit/main/"
  theme:
    description: "Set the theme"
    required: false
    default: material
  config:
    description: "Configuration file"
    required: false
  version:
    description: "Version to publish"
    required: false
    default: "latest"
  default_version:
    description: "Default version"
    required: false
    default: "latest"
  push:
    description: "Push to remote"
    required: false
    default: "1"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - deploy.sh
