name: 'MkDocs Simple action'
description: 'Generate a configuration free mkdocs site'
branding:
  icon: 'book'  
  color: 'green'
inputs:
  publish_branch:
    description: 'Set a target branch for deployment.'
    required: false
    default: 'gh-pages'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env: 
    BRANCH_NAME: ${{ inputs.publish_branch }}
    REPO_URL: http://github.com/${{ github.repository }} 
    SITE_NAME: ${{ github.repository }}
    SITE_URL: http://{{ github.repository_owner }}.github.io/${{ github.event.repository.name }}
  args:
    - deploy.sh
