name: Publish docs

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.5
      - name: Set up Python 3
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Build Docs
        run: ./build.sh
      - name: Publish Docs
        uses: ./
