name: Publish Docs

on:
  release:
    types: [published]
  push:
    branches: [docs/**]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Docs
        uses: ./
