name: docs

on:
  push:
    branches: [main]
  release:
    types: [published]
  workflow_dispatch:

# Add a concurrency group so that doc publish doesn't interfere with each other.
concurrency: 
  group: publish-docs

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Publish dev docs
        uses: ./
        with:
          version: dev
      - name: Publish Release docs
        if: ${{ github.event.release.tag_name }}
        uses: ./
        with:
          version: ${{ github.event.release.tag_name }} latest
          default_version: ${{ github.event.release.tag_name }}
