name: Publish docs

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: 3
          cache: 'pip'
      - run: pip install -r requirements.txt
      - name: Build Docs
        run: ./build.sh
      - name: Setup environment
        run: |
          echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV
      - name: Publish Docs
        uses: ./
        with:
          version: ${{ env.VERSION }} latest
