name: release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-pypi:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"
          cache: 'pip'
      - name: Build distributions
        run: |
          python -m pip install --upgrade pip
          python -m pip install build hatchling
          python -m build
      - name: Store the distribution packages
        uses: actions/upload-artifact@v5
        with:
          name: python-package-distributions
          path: dist/

  release-pypi:
    name: Upload release to PyPI
    needs:
    - build-pypi
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/mkdocs-simple-plugin
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing
    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v8
      with:
        name: python-package-distributions
        path: dist/
    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1

  release-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup environment
        run: |
          echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV
      - name: Login to DockerHub
        uses: docker/login-action@v4.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push docker image
        uses: docker/build-push-action@v7.0.0
        with:
          context: .
          file: ./Dockerfile
          tags: |
            althack/mkdocs-simple-plugin:latest
            althack/mkdocs-simple-plugin:${{ env.VERSION }}
          push: true
