name: Test Action

on:
  push:
    branches: [workflows/**]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Docs
        uses: ./
        with:
          publish_branch: gh-pages-test
