# TODO remove before merge
name: Test docker push 
on:
  push:
    tags:
      - "v*-test-docker"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get version
        run: |
          echo "::set-env name=VERSION::$(/usr/bin/git tag --list | sed 's|.*v\([0-9\.]*\).*|\1|')"
      - name: Bump version
        run: |
          echo "v${{ env.VERSION }}"
      - name: Build docker image
        uses: elgohr/Publish-Docker-Github-Action@2.14
        with:
          name: athackst/mkdocs-simple-plugin
          tags: "latest, v${{ env.VERSION }}"
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
